### ISSUE TITLE
SwaggerModule.createDocument issue

### ISSUE THREAD

**Issue by dinohand** [dinohand/middleware#1]
1. biz/model ~ 관련 코딩이후 swagger 오류 발생함
-  DTO 관련 로직, POST handler 관련 로직이 들어갔음

2. main.ts에서 

```
  //=======================================================================
  // Swagger Set

  const swaggerConfig = new DocumentBuilder()
    .setTitle('GP1 API document')
    .setDescription('The GP1 API(REST,GraphQL) description')
    .setVersion('1.0')
    .build();

   const document = SwaggerModule.createDocument(app, swaggerConfig);
   SwaggerModule.setup(__APIDOC_URI__, app, document);

```
에서 SwaggerModule.createDocument function 실행시 오류 발생됨
지금은 커멘트 처리함
```

D:\Git\middleware\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:70
        const { prototype } = type;
                ^
TypeError: Cannot destructure property 'prototype' of 'type' as it is undefined.
    at SchemaObjectFactory.extractPropertiesFromType (D:\Git\middleware\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:70:17)
    at SchemaObjectFactory.exploreModelSchema (D:\Git\middleware\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:92:41)
    at D:\Git\middleware\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:33:36
    at Array.map (<anonymous>)
    at SchemaObjectFactory.createFromModel (D:\Git\middleware\node_modules\@nestjs\swagger\dist\services\schema-object-factory.js:20:45)
    at exploreApiParametersMetadata (D:\Git\middleware\node_modules\@nestjs\swagger\dist\explorers\api-parameters.explorer.js:33:55)
    at D:\Git\middleware\node_modules\@nestjs\swagger\dist\swagger-explorer.js:72:45
    at Array.reduce (<anonymous>)
    at D:\Git\middleware\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:104
    at D:\Git\middleware\node_modules\lodash\lodash.js:13469:38
```

**Comment by dinohand** [comment]
model.module에 interface, dto, enum 등등 데이터 관련 정의 로직을 넣은 것이 swagger와 충돌함
nest g res <모듈명>으로 각각의 dto, entities를 분리하여 생성하면 충돌되지 않음

**Comment by dinohand** [comment]
model.module에 interface, dto, enum 등등 데이터 관련 정의 로직을 넣은 것이 swagger와 충돌함
nest g res <모듈명>으로 각각의 dto, entities를 분리하여 생성하면 충돌되지 않음
